# Generated by Django 5.2.13 on 2026-05-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('estimated_resolution_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'region'], name='network_net_is_acti_85c2a0_idx')],
            },
        ),
    ]
