# Generated by Django 5.2.13 on 2026-05-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountusage',
            new_name='customers_a_account_3b8410_idx',
            old_name='cust_usage_acct_dates',
        ),
    ]
